---
title: "for"
format: html
editor: source
self-contained: true
---

Load libraries
```{r, message = FALSE, warning = FALSE, echo = F, error=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, error=FALSE)
source(here::here("R/libraries.R"))
source(here::here("R/colors.R"))
source(here::here("R/functions.R"))
```

Load data
```{r}
df <- readxl::read_excel(here::here('data-raw/clen_data.xlsx')) %>% 
    dplyr::mutate(id = as.factor(id)) %>% 
    dplyr::mutate(trial = as.factor(trial)) %>%
    dplyr::mutate(time = factor(time, levels = c("pre", "post"))) %>%
    dplyr::mutate(treatment = factor(treatment, levels = c("PLA", "CLEN"))) %>%
    dplyr::group_by(id, treatment) %>% 
    dplyr::mutate(delta_lean = lean - lean[time == "pre"]) %>% 
    dplyr::mutate(delta_fat = fat - fat[time == "pre"]) %>% 
    dplyr::mutate(delta_fat_p = fat_p - fat_p[time == "pre"]) %>% 
    dplyr::mutate(delta_vo2max = vo2max - vo2max[time == "pre"]) %>% 
    dplyr::mutate(delta_ippo = ippo - ippo[time == "pre"]) %>% 
    dplyr::mutate(delta_appo = appo - appo[time == "pre"]) %>% 
    dplyr::mutate(delta_ppo = ppo - ppo[time == "pre"]) %>%
    dplyr::mutate(delta_mpo = mpo - mpo[time == "pre"]) %>% 
    dplyr::mutate(delta_mvc = mvc - mvc[time == "pre"]) %>% 
    dplyr::mutate(delta_lv_mass = lv_mass - lv_mass[time == "pre"]) %>% 
    dplyr::mutate(delta_lv_sv = lv_sv - lv_sv[time == "pre"])
    
```

# Lean
```{r}
lean <- barplot(df, variable = "delta_lean", ylab = "Change in lean mass (kg)")

ggsave(here::here('data/figures/lean.svg'), width = 60, height = 50, units = "mm")
```

Lean stats
```{r}
#Fit model
lm <- lmer(lean ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

#Test normal distribution
qqmath(lm)

```

# Fat
```{r}
fat <- barplot(df, variable = "delta_fat", ylab = "Change in fat mass (kg)")

ggsave(here::here('data/figures/fat.svg'), width = 60, height = 50, units = "mm")
```

Fat stats
```{r}
#Fit model
lm <- lmer(fat ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated margingal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# Fat percent
```{r}
fat_p <- barplot(df, variable = "delta_fat_p", ylab = "Change in fat percent (%.)")

ggsave(here::here('data/figures/fat_p.svg'), width = 60, height = 50, units = "mm")

```

Fat percent stats
```{r}
#Fit model
lm <- lmer(fat_p ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)
```

# VO2max
```{r}
vo2max <- barplot(df, variable = "delta_vo2max", ylab = "Change in VO2max (mL/min)")

ggsave(here::here('data/figures/vo2max.svg'), width = 60, height = 50, units = "mm")

```

VO2max stats
```{r}
#Fit model
lm <- lmer(vo2max ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# iPPO
```{r}
ippo <- barplot(df, variable = "delta_ippo", ylab = "Change in Wmax (W)")

ggsave(here::here('data/figures/ippo.svg'), width = 60, height = 50, units = "mm")

```

ippo stats
```{r}
#Fit model
lm <- lmer(ippo ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# appo
```{r}
appo <- barplot(df, variable = "delta_appo", ylab = "Change in aerobic peak power (W)")

ggsave(here::here('data/figures/appo.svg'), width = 60, height = 50, units = "mm")

```

aPPO stats
```{r}
#Fit model
lm <- lmer(appo ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# MVC
```{r}
mvc <- barplot(df, variable = "delta_mvc", ylab = "Change in MVC (Nm)")

ggsave(here::here('data/figures/mvc.svg'), width = 60, height = 50, units = "mm")

```

MVC stats
```{r}
#Fit model
lm <- lmer(mvc ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# Sprint PPO
```{r}
ppo <- barplot(df, variable = "delta_ppo", ylab = "Change in PPO (W)")

ggsave(here::here('data/figures/ppo.svg'), width = 60, height = 50, units = "mm")

```

Sprint PPO stats
```{r}
#Fit model
lm <- lmer(ppo ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# Sprint MPO
```{r}
mpo <- barplot(df, variable = "delta_mpo", ylab = "Change in MPO (W)")

ggsave(here::here('data/figures/mpo.svg'), width = 60, height = 50, units = "mm")

```

Sprint MPO stats
```{r}
#Fit model
lm <- lmer(mpo ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# LV mass
```{r}
lv_mass <- barplot(df, variable = "delta_lv_mass", ylab = "Change in LV mass (g)")

ggsave(here::here('data/figures/lv_mass.svg'), width = 60, height = 50, units = "mm", dpi = 600)

```

LV mass stats
```{r}
#Fit model
lm <- lmer(lv_mass ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# LV SV
```{r}
lv_sv <- barplot(df, variable = "delta_lv_sv", ylab = "Change in SV (mL)")

ggsave(here::here('data/figures/lv_sv.svg'), width = 60, height = 50, units = "mm", dpi = 600)

```

LV SV stats
```{r}
#Fit model
lm <- lmer(lv_sv ~ treatment * time + (1|id), data = df, REML=FALSE)

#Show overall ANOVA output
anova(lm)

#Show estimated marginal means
emm <- emmeans(lm, specs = ~ time * treatment, pbkrtest.limit = 5000, lmerTest.limit = 5000)

# Define specific contrasts for post-pre comparisons for PLA and CLEN
contrasts <- list(
    "post - pre for PLA" = c(-1, 1, 0, 0),  # Compare post to pre for PLA
    "post - pre for CLEN" = c(0, 0, -1, 1)  # Compare post to pre for CLEN
)

contrast_results <- contrast(emm, contrasts)

summary(contrast_results, infer = TRUE)

```

# Export layout
```{r}
#Export layout
plots <- list(lean, fat, fat_p, vo2max, ippo, appo, mvc, ppo, mpo)

combined_plots <- patchwork::wrap_plots(plots, ncol = 3, nrow = 3)

ggsave(plot = combined_plots, here::here('data/figures/combined_plots.svg'), width = 150, height = 150, units = "mm")
```

# Correlations
```{r}
df %>% 
    dplyr::filter(treatment == "CLEN") %>% 
    dplyr::filter(time == "post") %>% 
    ggplot(aes(x = weight, y = delta_lean))+
        geom_point(size = 4)+
    geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.25)+
        theme(
            panel.background = element_blank(),
            panel.border = element_rect(colour = "black", fill=NA, linewidth = 0.25),
            panel.grid.minor=element_blank(),
            panel.grid.major = element_blank(),
            plot.background = element_blank(),
            axis.line = element_blank(),
            axis.text = element_text(color = "black", size = 10),
            #axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
            text = element_text(size = 10, family="Source Sans Pro", color = "black"),
            axis.title = element_text(size = 10, family="Source Sans Pro"),
            legend.title = element_blank(),
            legend.key = element_blank(),
            legend.key.size = (unit(3, "mm")),
            #legend.position = c(0.05, 0.99), 
            #legend.justification = c(0, 1), 
            #legend.box.just = "left", 
            #legend.margin = margin(0, 0, 0, 0),
            legend.background = element_blank(),
            legend.box.background = element_blank(),
            title = element_text(size = 6),
            strip.background = element_blank()
            )

```
No apparent effect of relative dose.

