---
title: "for"
format: html
editor: source
self-contained: true
---

Load libraries
```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, error=FALSE)
source(here::here("R/libraries.R"))
source(here::here("R/colors.R"))
source(here::here("R/functions.R"))
```

Load data
```{r}
df <- readxl::read_excel(here::here('data-raw/clen_data.xlsx')) %>% 
    dplyr::mutate(id = as.factor(id)) %>% 
    dplyr::mutate(trial = as.numeric(trial)) %>%
    dplyr::mutate(time = factor(time, levels = c("pre", "post"))) %>%
    dplyr::mutate(treatment = factor(treatment, levels = c("PLA", "CLEN"))) %>%
    dplyr::group_by(id) %>% 
    #Delta compared to first trial
    dplyr::mutate(delta_lean_carry_over = lean - lean[trial == "1"]) %>%
    dplyr::mutate(delta_fat_carry_over = fat - fat[trial == "1"]) %>%
    dplyr::ungroup() %>% 
    dplyr::group_by(id, treatment) %>% 
    #Whole body
    dplyr::mutate(delta_lean = lean - lean[time == "pre"]) %>%
    dplyr::mutate(delta_fat = fat - fat[time == "pre"]) %>% 
    dplyr::mutate(delta_fat_p = fat_p - fat_p[time == "pre"]) %>% 
    #Leg
    dplyr::mutate(delta_leg_lean = leg_lean - leg_lean[time == "pre"]) %>%
    dplyr::mutate(delta_leg_fat = leg_fat - leg_fat[time == "pre"]) %>% 
    dplyr::mutate(delta_leg_fat_p = leg_fat_p - leg_fat_p[time == "pre"]) %>% 
    #Arm
    dplyr::mutate(delta_arm_lean = arm_lean - arm_lean[time == "pre"]) %>%
    dplyr::mutate(delta_arm_fat = arm_fat - arm_fat[time == "pre"]) %>% 
    dplyr::mutate(delta_arm_fat_p = arm_fat_p - arm_fat_p[time == "pre"]) %>% 
    #Torso
    dplyr::mutate(delta_torso_lean = torso_lean - torso_lean[time == "pre"]) %>%
    dplyr::mutate(delta_torso_fat = torso_fat - torso_fat[time == "pre"]) %>% 
    dplyr::mutate(delta_torso_fat_p = torso_fat_p - torso_fat_p[time == "pre"]) %>%
    #Aerobic
    dplyr::mutate(delta_vo2max = vo2max - vo2max[time == "pre"]) %>% 
    dplyr::mutate(delta_kondital = kondital - kondital[time == "pre"]) %>% 
    dplyr::mutate(delta_ippo = ippo - ippo[time == "pre"]) %>% 
    dplyr::mutate(delta_appo = appo - appo[time == "pre"]) %>%
    #Anaerobic
    dplyr::mutate(delta_ppo = ppo - ppo[time == "pre"]) %>%
    dplyr::mutate(delta_mpo = mpo - mpo[time == "pre"]) %>%
    #Cardiac
    dplyr::mutate(delta_lv_mass = lv_mass - lv_mass[time == "pre"]) %>% 
    dplyr::mutate(delta_lv_sv = lv_sv - lv_sv[time == "pre"]) %>% 
    dplyr::mutate(delta_hr = hr - hr[time == "pre"]) %>% 
    dplyr::mutate(delta_co = co - co[time == "pre"]) %>% 
    dplyr::mutate(delta_ef = ef - ef[time == "pre"]) %>% 
    #MVC
    dplyr::mutate(delta_mvc = mvc - mvc[time == "pre"]) %>% 
    dplyr::mutate(delta_tpot = tpot - tpot[time == "pre"]) %>% 
    dplyr::mutate(delta_tpt = tpt - tpt[time == "pre"]) %>% 
    dplyr::mutate(delta_hrt = hrt - hrt[time == "pre"]) %>% 
    dplyr::mutate(delta_va = va - va[time == "pre"]) %>%
    #Ungroup
    dplyr::ungroup()
    
```

Lean vs. fat
```{r}
df %>% 
    dplyr::filter(time == "post") %>% 
    ggplot(aes(x = delta_lean, y = delta_fat, color = treatment))+
    geom_point(size = 4,
               shape = 16)+
    geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.25)+
    geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.25)+
    theme(
        panel.background = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, linewidth = 0.1),
        panel.grid.minor=element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "white"),
        axis.line = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.ticks = element_line(linewidth = 0.1),
        axis.title = element_text(size = 8, family="Source Sans Pro"),
        axis.title.x = element_text(size = 8, family="Source Sans Pro"),
        axis.title.y = element_text(size = 8, family="Source Sans Pro"),
        text = element_text(size = 10, family="Source Sans Pro"),
        legend.title = element_blank(),
        legend.key = element_blank(),
        strip.background = element_blank()
    )+
    scale_color_manual(
        values = c("PLA" = pla_color, "CLEN" = clen_color))+
    labs(x = "Change in lean mass (kg)",
         y = "Change in fat mass (kg)")

ggsave(here::here('data/figures/cor_lean_vs_fat.svg'), height = 100, width = 200, units = "mm")
```


